### ISSUE TITLE
fontsize ocassionally resetting

### ISSUE THREAD

**Issue by 3demax** [Guff/lualock#2]
style{ color = "black", font = "Sans 26", 
        x = sxcenter - 150/2 - 24, 
        y = input_top + 50, 
        off_x = 10,
        off_y = 10, 
        width = 199, 
        height = 50 
}

From "Sans 26" as it have to be to something like "Sans 10" (looks alot like default font and fontsize)
this happens sometimes and is hard to reproduce.
Maybe entering text and deleting chars few times.

I'm in master branch, commit 4951004a2abb6e116aa5972d2dbedf862dadc03e

**Comment by Guff** [comment]
I think I fixed it. Let me know if it persists.
