### ISSUE TITLE
weird odious text widget border_width behaviour

### ISSUE THREAD

**Issue by 3demax** [Guff/lualock#4]
Weird things happen to odious text widget when border_width is less than 2. Text then looks like cropped. 

user_text = odious.widget.text{ text = os.getenv("USER"), font = "Sans 24", color = "black",  x = sxcenter - 92, y = input_top + 10,  border_color = "grey", border_width = 2 }
http://i.imgur.com/RAAq3.png

user_text = odious.widget.text{ text = os.getenv("USER"), font = "Sans 24", color = "black",  x = sxcenter - 92, y = input_top + 10,  border_color = "grey", border_width = 0 }
http://i.imgur.com/8IdFQ.png

And even worse with long text
http://i.imgur.com/XB2yY.png
http://i.imgur.com/ycWUA.png

**Comment by Guff** [comment]
Alright, I think I fixed it. If I missed something, just let me know.
